# name of your application
APPLICATION = sizeof_pktbuf

DISABLE_MODULE = auto_init
USEMODULE += fmt

# If no BOARD is found in the environment, use this default:
BOARD ?= native

QUIET ?= 1

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT/

include $(RIOTBASE)/Makefile.include
