APPLICATION := $(shell basename $(CURDIR))_$(shell basename $(realpath $(CURDIR)/..))

BOARD ?= iotlab-m3

RIOTBASE ?= $(CURDIR)/../../../../RIOT

DISABLE_MODULE += auto_init

USEMODULE += inet_csum
USEMODULE += netdev2_ieee802154
USEMODULE += netdev2_test
USEMODULE += xtimer

CFLAGS += -DAPPLICATION_NAME='"$(APPLICATION)"'

QUIET ?= 1

include $(RIOTBASE)/Makefile.include
