.PHONY: all clean distclean

all:
	$(MAKE) -C emb6 $@
	$(MAKE) -C gnrc $@
	$(MAKE) -C lwip $@

clean:
	$(MAKE) -C emb6 $@
	$(MAKE) -C gnrc $@
	$(MAKE) -C lwip $@

distclean:
	$(MAKE) -C emb6 $@
	$(MAKE) -C gnrc $@
	$(MAKE) -C lwip $@
