USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_conn_udp
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_netdev2
ifeq (1,$(RPL_STACK))
  USEMODULE += gnrc_rpl
endif
USEMODULE += gnrc_udp

include ../Makefile.common
