USEMODULE += lwip_conn_udp
USEMODULE += lwip_ipv6
USEMODULE += lwip_netdev2
USEMODULE += lwip_netif
USEMODULE += lwip_sixlowpan
USEMODULE += lwip_udp

CFLAGS += -DMEM_SIZE="(THREAD_STACKSIZE_DEFAULT + 10592)"

include ../Makefile.common
