USEMODULE += lwip_conn_udp
USEMODULE += lwip_ipv6
USEMODULE += lwip_netdev2
USEMODULE += lwip_netif
USEMODULE += lwip_sixlowpan
USEMODULE += lwip_udp
USEMODULE += inet_csum

include ../Makefile.common
