USEMODULE += gnrc_conn_udp
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_netdev2
USEMODULE += gnrc_sixlowpan_iphc_nhc
USEMODULE += gnrc_sixlowpan_router_default
USEMODULE += gnrc_udp

include ../Makefile.common
