name: Build applications

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        app:
          - lndw22_doc/client
    container: riot/riotbuild
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build application
      run: make -C ${{ matrix.app }} -j all
